### ISSUE TITLE
collaborate with routes-router

### ISSUE THREAD

**Issue by Raynos** [pluma0/routes-http#1]
https://github.com/Raynos/routes-router

We seem to have very similar ideas. Maybe we can contribute to each others modules.

**Comment by pluma** [comment]
Sure. I mostly wrote `routes-http` because I was unhappy with a few design decisions of `routes-router`:
- `router` uses special ChildRouter objects and is generally very explicit about nested routes. I wanted something more composable and agnostic.
- `router` handles 404 and 405 errors autonomously, in the case of 405 this is actually due to the dependency on `http-methods`. I wanted something that just throws meaningful exceptions (leading me to write `httperr`) my way and doesn't touch the response object.

I think `routes-router` is pretty good at what it does as-is, it just didn't meet my requirements.

**Comment by Raynos** [comment]
@pluma I'm happy to have improvements to the child router, if there is a way to get rid of it, i'd be good!

As for 404, do you prefer a single error handler compared to an error handler & 404 handler ?

As for 405, I can fix `http-methods` to not do 405 handling for you.

I like `httperr` :)

**Comment by pluma** [comment]
I'm using `routes-http` and `httperr` in a closed-source project I am working on at the moment, which has influenced some of my decisions:
- My views generally take care of any immediate error handling internally, so the only situation in which `routes-http` has to use an error handler directly is in the case of 404s and 405s. If my views do throw an error intentionally it will be wrapped in a `httperr` to provide meaningful feedback to the user (not every "internal server error" should be a 500 -- e.g. malformed JSON requests).
- Any non-fatal error is eventually handled by a centralized error handler that attempts to send an appropriate HTTP response to the user and logs it if appropriate. This handler is added to the response object, passed to `routes-http` (for 404s, 405s and synchronous exceptions) and bound to the domain `routes-http` is called in.
- Related views are defined in the same file and export a function that takes the relevant configuration (proxies to the database and session store mostly) and returns a `router`, which is then "mounted" in the appropriate place. The views themselves just contain glue code as promise chains, allowing me to test the actual logic in isolation.

As for eliminating the ChildRouter: the benefit of your approach is that you could theoretically subclass Router in other ways and use them interchangeably: your ChildRouter is responsible for figuring out where it is in the routing tree and what to do, so the parent Router can remain completely ignorant of its existence. This also means there's no unused logic pertaining to ChildRouters involved if you don't use them.

The approach I took was to merge the functionality of ChildRouter into the router itself. `routes-http` wraps the `addRoute` method from `routes` to check if the "view" looks like another router and modifies the URL pattern if neccessary (this obviously isn't compatible with regular expressions as URL patterns).

Because `addRoute` always appends a `*` to the URL if the view is another router, the route handler does not actually need to know where it is nested: if it is invoked as a view, it is passed the globs array, which already contains the relative URL it is interested in. This means the same router could hypothetically be nested in several different places -- which is probably a bit silly.

As for `http-methods`: the HTTP method dispatch logic in `routes-http` currently consists of about 4 LLOC and `http-methods` simply does more than I want: although I do use `jsonBody` in my views, how I use it exactly depends on the view, e.g. the login currently cuts the client off at 1kb whereas a more complex view might want to allow several orders of magnitude more than that (yes, I'm obsessive). Lack of control over these details is part of the reason I'm not use express in the first place ;)

**Comment by Raynos** [comment]
I want to merge `ChildRouter` into `Router` for `routes-router` today. I think it should be possible using a similar technique to what your doing. The only thing I don't like is the merging of the parent routers splats / params with the child routes splats / params.

As for error handling, I should mix it up to be less opinionated and use `httperr`
