### ISSUE TITLE
Browser version?

### ISSUE THREAD

**Issue by kokujin** [pluma0/routes-http#2]
Hi there!

Would there be a browser version someday?

**Comment by pluma** [comment]
You should be able to use it with browserify as it is, but because [httperr](https://github.com/pluma/httperr) and [routes](https://github.com/aaronblohowiak/routes.js) are currently only available as CommonJS modules I can't offer an AMD or legacy version for browsers.

If you just want something to handle routing in the browser, you could use `routes` directly (it has no dependencies, so you could easily convert it).
